name: Publish packages

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  node-version: "18"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains 1 job called "build"

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ./node_modules/
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish Oraidex Common
        id: publish-common
        continue-on-error: true
        run: yarn deploy packages/oraidex-common
        env:
          CI: false
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Universal-swap
        id: publish-universal-swap
        continue-on-error: true
        run: yarn deploy packages/universal-swap
        env:
          CI: false
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Oraidex contracts-sdk
        id: publish-oraidex-contracts-sdk
        continue-on-error: true
        run: yarn deploy packages/contracts-sdk
        env:
          CI: false
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Oraidex contracts-build
        id: publish-oraidex-contracts-build
        continue-on-error: true
        run: yarn deploy packages/contracts-build
        env:
          CI: false
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Oraidex oraiswap-v3
        id: publish-oraiswap-v3
        continue-on-error: true
        run: yarn deploy packages/oraiswap-v3
        env:
          CI: false
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Send result via discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          username: "GitBot"
          message: "Repo oraidex-sdk has just published:\n- Oraidex Common: ${{ steps.publish-common.outcome }}\n- Universal-swap: ${{ steps.publish-universal-swap.outcome }}\n- Oraidex contracts-sdk: ${{ steps.publish-oraidex-contracts-sdk.outcome }}\n- Oraidex contracts-build: ${{ steps.publish-oraidex-contracts-build.outcome }}\n- Oraiswap-v3: ${{ steps.publish-oraiswap-v3.outcome }}."
